<a href="https://colab.research.google.com/github/exxom/Pytorch-Tutorial/blob/main/torch_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

**LISTS**

In [3]:
my_list=[[1,2,3,4,5],[6,7,8,9,10,11]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11]]

**NUMPY ARRAYS**

In [4]:
np1=np.random.rand(3)
np1

array([0.84223964, 0.46834679, 0.3355469 ])

In [5]:
np1.dtype

dtype('float64')

**TENSORS**


In [7]:
tensor_2d=torch.randn(3,4)
tensor_2d

tensor([[ 0.7938,  2.5708, -1.0490,  0.0125],
        [-1.1195, -1.3380, -0.5353, -0.3521],
        [ 0.4965,  0.3930, -1.1254,  0.3396]])

In [9]:
tensor_3d=torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
#creat tensor out of numpy

my_tensor=torch.tensor(np1)
my_tensor

tensor([0.8422, 0.4683, 0.3355], dtype=torch.float64)