<a href="https://colab.research.google.com/github/exxom/Pytorch-Tutorial/blob/main/torch_reshape_vs_view.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Reshape and View
my_torch=my_torch.reshape(2,5)
my_torch


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#Reshape if we don't know the number of items using -1
my_torch2=torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
my_torch2=my_torch2.reshape(3,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [ ]:
my_torch4=torch.arange(10)
my_torch4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch4=my_torch4.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch5=torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch6=my_torch5.reshape(2,5)
my_torch6

tensor([[  0,   1, 555,   3,   4],
        [  5,   6,   7,   8,   9]])

In [ ]:
my_torch5[2]=555
my_torch5

tensor([  0,   1, 555,   3,   4,   5,   6,   7,   8,   9])

In [ ]:
#slices
my_torch5[2:5]

tensor([555,   3,   4])

In [ ]:
# grab a specific item
my_torch5[6]

tensor(6)

In [ ]:
#grab & slice
my_torch7=my_torch5.reshape(5,2)
my_torch7

tensor([[  0,   1],
        [555,   3],
        [  4,   5],
        [  6,   7],
        [  8,   9]])

In [ ]:
my_torch7[:,1]

tensor([1, 3, 5, 7, 9])

In [ ]:
my_torch7[:,0]

tensor([  0, 555,   4,   6,   8])

In [ ]:
#return column
my_torch7[]